services:
  postgres:
    image: postgres:16
    container_name: pg16
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: whitenote
    ports:
      - "5925:5432"
    volumes:
      - pg16_data:/var/lib/postgresql/data

volumes:
  pg16_data:
